In [2]:
import numpy as np

In [23]:
X = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
A = X.T
A

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [24]:
mean_a = A.mean(axis = 0)
mean_a

array([2. , 8.4])

In [27]:
a_centered = A - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [39]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp / ((a_centered.shape[0] - 1))

2.0

In [37]:
cov = np.cov(X)
cov

array([[1. , 2. ],
       [2. , 4.3]])