In [1]:
import numpy as np

In [2]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
a + b

array([[ 5, -3],
       [ 3,  5]])

In [3]:
np.dot(a, b)

array([[  4, -11],
       [ 12,  -3]])

In [4]:
np.dot(b, a)

array([[ 1, -8],
       [15,  0]])

In [6]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
3 * a + (-2) * b + 4 * c

array([[ 11,  -5],
       [  9, -12]])

In [7]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [8]:
np.dot(A, A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [9]:
np.dot(A.T, A)

array([[45,  0],
       [ 0, 14]])

In [11]:
class Matrix:
    def __init__(self, matrix):
        self.matrix= matrix
    
    def __str__(self):
        return ','.join(map(str, self.matrix)).replace(']', '\n').replace('[', '').replace(',', '')
    
    def __add__(self, other):
        if len(self.matrix) == len(other.matrix):
            for row1, row2 in zip(self.matrix, other.matrix):
                if len(row1) != len(row2):
                    return f'Количество столбцов не равно, эти матрицы нельзя сложить'
            result = [[a + b for a, b in zip(row1, row2)] for row1, row2 in zip(self.matrix, other.matrix)]
            return ','.join(map(str, result)).replace(']', '\n').replace('[', '').replace(',', '')
        else:
            return f'Количество строк не равно, эти матрицы нельзя сложить'

    def __mul__(self, other):
        result = []
        try:
            for row in self.matrix:
                row_result = []
                for i in range(len(other.matrix[0])):
                    num = 0
                    for idx, el in enumerate(row):
                        num += (el * other.matrix[idx][i])
                    row_result.append(num)
                result.append(row_result)
            return ','.join(map(str, result)).replace(']', '\n').replace('[', '').replace(',', '')
        except:
            return f'Умножение матриц данной размерности невозможно'

In [12]:
m_1 = Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m_2 = Matrix([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(m_1)
print(m_2)
print(m_1 + m_2)

1 2 3
4 5 6
7 8 9

10 20 30
40 50 60
70 80 90

11 22 33
44 55 66
77 88 99



In [13]:
m_3 = Matrix([[4, 1], [5, -2], [2, 3]])
m_4 = Matrix([[ 4, 5, 2], [ 1, -2, 3]])
print(m_1 * m_2)
print(m_3 * m_4)
print(m_4 * m_3)

300 360 420
660 810 960
1020 1260 1500

17 18 11
18 29 4
11 4 13

45 0
0 14



In [14]:
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(b)

180.0

In [15]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
round(np.linalg.det(c), 2)

0.0

In [16]:
c = np.array([[-2, 7, -3], [4, -14, 6],[-3, 7, 13]])
np.linalg.det(c)

0.0

In [17]:
a = np.array([[1, 2, 3], [1, 1, 1],[2, 3, 4]])
np.linalg.matrix_rank(a)

2

In [18]:
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(a)

3