In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array(range(12, 24))
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [3]:
a = a.reshape(2, 6)
a

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
a = a.reshape(3, 4)
a

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
a = a.reshape(4, 3)
a

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [6]:
a = a.reshape(6, 2)
a

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [7]:
a = a.reshape(12, 1)
a

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [8]:
a = a.reshape(2, -1)
a

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
a = a.reshape(4, -1)
a

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [10]:
a = a.reshape(12, -1)
a

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [11]:
a = a.reshape(-1, 4)
a

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
a = a.reshape(-1, 2)
a

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [13]:
ar = np.random.normal(loc = 0.0, scale = 1.0, size = (3, 4))

In [14]:
c = ar.flatten()
print(c)

[-2.88633517  1.7304775  -0.9780005   0.22527781  0.07709006  0.79674186
  0.59594932 -0.16111249 -0.9804793  -1.0869394  -0.38550335  1.27170808]


In [18]:
a = np.array(range(20, 0, -2))
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [20]:
b = a.reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [48]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
v.size

10

In [50]:
a = np.array(range(0, 12))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [59]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [64]:
d = np.linalg.det(B)
d

0.0

In [65]:
B_inv = np.linalg.inv(B)

LinAlgError: Singular matrix

In [66]:
np.random.seed(42)

In [68]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [69]:
C = c.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [80]:
D = np.add(C * 10, B)
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [76]:
D_d = np.linalg.det(D)
D_d

-28511999.999999944

In [78]:
D_rank = np.linalg.matrix_rank(D)
D_rank

4

In [79]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [81]:
positive = D_inv > 0
negative = D_inv < 0

In [82]:
D_inv[positive] = 1
D_inv[negative] = 0
print(D_inv)

[[1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 1. 0.]]


In [83]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])